### PR TITLE
Create new url summary function

### PR DESCRIPTION
**Pull request by capjamesg**
This PR implements an [auto URL summary](https://indieweb.org/auto-url-summary) function that produces a one-sentence summary of the contents of given URLs.

The PR includes various rules derived from the [CASSIS auto_url_summary](https://github.com/tantek/cassis/blob/master/cassis-lab.php#L52) function, implemented after discussion with @tantek on the usefulness of auto URL summaries.

This PR includes documentation and a test suite to accompany the function.

### CODE REVIEW

**Review by tantek — CHANGES_REQUESTED** [review]
This is a decent first cut, however I think either the code for summarizing a URL should stay flat (not call any functions that hide some specific domains / summarizing) in the short term or it should be redesigned completely to use data instead of if/else (that's my plan for the PHP version and why it's in cassis-lab instead of cassis.js core). Instead of partially structuring it, my plan was always to convert *all* the if/else logic into something that uses a table of domains, perhaps segments/fragments, and text equivalents.
I fear that any local code structure optimization will actually increase the barrier to overall understanding and a larger rewrite of the functionality.

**Comment by capjamesg** [comment]
@angelogladding and I were able to come up with a more elegant solution to this problem that avoids having to write individual functions and if statements for each new pattern to match.

We now have a dictionary of domains that are mapped to a list of tuples. This list of tuples contains patterns to match against and values to return if the pattern matches. This approach lets us separate the match pattern / response values from the logic of the program.

@tantek would you mind providing feedback on our new implementation (same files as before)?

**Comment by capjamesg** [comment]
Note: I need to add a call to canonicalize_url to ensure results are consistent with www.

**Review by tantek — APPROVED** [review]
This is a huge improvement! Move forward with this update and we’ll see how well it works for more domains.

**Pull request merged**
