### PR TITLE
Add CI Workflow

### LINKED ISSUE #21: Add CI
Add a GitHub action to run tox for each PR so we can make sure every merge passes all tests / linting.

### PR DESCRIPTION
**Pull request by jamesvandyne**
This PR adds a GitWork Actions Workflow to run tox with each branch / merge that we push. This will help us make sure that all branches don't break tests and we can maintain high quality.

Note this is branches from refactor_tests as it fixes some of the lint / typecheck errors (though not all). Refactor tests ( #20 ) should be merged before this branch.

### CODE REVIEW

**Comment by capjamesg** [comment]
I have merged #20 into main. Thank you for the heads up regarding the correct order of operations in which to address these pull requests.

Should we address all linting issues before merging this into the main branch? We'll get a "Some checks were not successful" error message until we have addressed those issues. I ran the CI workflow for this commit again after merging the refactor_tests branch into main and still see errors.

I am open to either option. It might be worth creating an issue to track linting issues.

**Comment by jamesvandyne** [comment]
@capjamesg I think we should merge it and then make a separate PR to be merged before new functionality / tests to fix the lint errors and type errors. I think there's a setting in GitHub where we can then prevent PRs from merging that don't pass all checks, so we don't break it going forward.

**Comment by capjamesg** [comment]
Sounds good. I have just merged this PR into the main branch.

**Review by capjamesg — COMMENTED** [review]
Looks good to me!

**Pull request merged**
